export const accountsFiltersConfig = [
    { key: 'activeAccounts', label: 'Active Accounts' },
    { key: 'inactiveAccounts', label: 'Inactive Accounts' },
    { key: 'accountType', label: 'Account Type' },
    { key: 'industry', label: 'Industry' },
    { key: 'rating', label: 'Rating' },
    { key: 'touchedRecords', label: 'Touched Records' },
    { key: 'untouchedRecords', label: 'Untouched Records' },
    { key: 'recordAction', label: 'Record Action' },
    { key: 'relatedRecordsAction', label: 'Related Records Action' },
    { key: 'locked', label: 'Locked' },
    { key: 'deals', label: 'Deals' },
    { key: 'dealAmount', label: 'Deal Amount' },
    { key: 'dealStage', label: 'Deal Stage' },
    { key: 'dealOwner', label: 'Deal Owner' },
    { key: 'dealClosingDate', label: 'Deal Closing Date' },
    { key: 'contacts', label: 'Contacts' }
  ];
  
  export const accountsFieldsConfig = [
    { key: 'accountName', label: 'Account Name' },
    { key: 'accountNumber', label: 'Account Number' },
    { key: 'accountOwner', label: 'Account Owner' },
    { key: 'accountSite', label: 'Account Site' },
    { key: 'accountType', label: 'Account Type' },
    { key: 'annualRevenue', label: 'Annual Revenue' },
    { key: 'billingCity', label: 'Billing City' },
    { key: 'billingState', label: 'Billing State' },
    { key: 'billingCountry', label: 'Billing Country' },
    { key: 'billingZip', label: 'Billing Zip' },
    { key: 'shippingCity', label: 'Shipping City' },
    { key: 'shippingState', label: 'Shipping State' },
    { key: 'shippingCountry', label: 'Shipping Country' },
    { key: 'shippingZip', label: 'Shipping Zip' },
    { key: 'createdBy', label: 'Created By' },
    { key: 'createdTime', label: 'Created Time' },
    { key: 'employees', label: 'Employees' },
    { key: 'fax', label: 'Fax' },
    { key: 'industry', label: 'Industry' },
    { key: 'lastActivityTime', label: 'Last Activity Time' },
    { key: 'modifiedBy', label: 'Modified By' },
    { key: 'modifiedTime', label: 'Modified Time' },
    { key: 'ownership', label: 'Ownership' },
    { key: 'parentAccount', label: 'Parent Account' },
    { key: 'phone', label: 'Phone' },
    { key: 'rating', label: 'Rating' },
    { key: 'sicCode', label: 'SIC Code' },
    { key: 'tag', label: 'Tag' },
    { key: 'tickerSymbol', label: 'Ticker Symbol' },
    { key: 'website', label: 'Website' }
  ];
  