export const contactsFiltersConfig = [
    { key: 'touchedRecords', label: 'Touched Records' },
    { key: 'untouchedRecords', label: 'Untouched Records' },
    { key: 'recordAction', label: 'Record Action' },
    { key: 'relatedRecordsAction', label: 'Related Records Action' },
    { key: 'locked', label: 'Locked' },
    { key: 'latestEmailStatus', label: 'Latest Email Status' },
    { key: 'activities', label: 'Activities' },
    { key: 'notes', label: 'Notes' },
    { key: 'deals', label: 'Deals' },
    { key: 'campaigns', label: 'Campaigns' },
    { key: 'cadences', label: 'Cadences' }
  ];
  
  export const contactsFieldsConfig = [
    { key: 'accountName', label: 'Account Name' },
    { key: 'assistant', label: 'Assistant' },
    { key: 'asstPhone', label: 'Asst Phone' },
    { key: 'contactName', label: 'Contact Name' },
    { key: 'contactOwner', label: 'Contact Owner' },
    { key: 'createdBy', label: 'Created By' },
    { key: 'createdTime', label: 'Created Time' },
    { key: 'dateOfBirth', label: 'Date of Birth' },
    { key: 'department', label: 'Department' },
    { key: 'email', label: 'Email' },
    { key: 'emailOptOut', label: 'Email Opt Out' },
    { key: 'fax', label: 'Fax' },
    { key: 'firstName', label: 'First Name' },
    { key: 'homePhone', label: 'Home Phone' },
    { key: 'lastActivityTime', label: 'Last Activity Time' },
    { key: 'lastName', label: 'Last Name' },
    { key: 'leadSource', label: 'Lead Source' },
    { key: 'mailingCity', label: 'Mailing City' },
    { key: 'mailingCountry', label: 'Mailing Country' },
    { key: 'mailingState', label: 'Mailing State' },
    { key: 'mailingStreet', label: 'Mailing Street' },
    { key: 'mailingZip', label: 'Mailing Zip' },
    { key: 'mobile', label: 'Mobile' },
    { key: 'modifiedBy', label: 'Modified By' },
    { key: 'modifiedTime', label: 'Modified Time' },
    { key: 'otherCity', label: 'Other City' },
    { key: 'otherCountry', label: 'Other Country' },
    { key: 'otherPhone', label: 'Other Phone' },
    { key: 'otherState', label: 'Other State' },
    { key: 'otherStreet', label: 'Other Street' },
    { key: 'otherZip', label: 'Other Zip' },
    { key: 'phone', label: 'Phone' },
    { key: 'reportingTo', label: 'Reporting To' },
    { key: 'salutation', label: 'Salutation' },
    { key: 'secondaryEmail', label: 'Secondary Email' },
    { key: 'skypeID', label: 'Skype ID' },
    { key: 'tag', label: 'Tag' },
    { key: 'title', label: 'Title' },
    { key: 'twitter', label: 'Twitter' },
    { key: 'unsubscribedMode', label: 'Unsubscribed Mode' },
    { key: 'unsubscribedTime', label: 'Unsubscribed Time' }
  ];