const dealsData = [
  {
    id: 1,
    dealName: 'Playboi Carti Endorsement',
    stage: 'Qualification',
    amount: '$480,000',
    closingDate: '2024-10-05',
    owner: 'Chris Evans',
    accountName: 'Opium LLC',
    contactName: 'Playboi Carti',
    type: 'Endorsement',
    source: 'Cold Call',
    nextStep: 'Follow up call',
    createdTime: '2024-07-07',
    modifiedTime: '2024-07-25',
    description: 'Endorsement deal for Playboi Carti.',
    email: 'playboicarti@example.com',
    phone: '555-000-0001',
    mailingCity: 'Los Angeles',
    mailingCountry: 'USA',
    mailingState: 'CA',
    mailingStreet: '456 Music Blvd',
    mailingZip: '90001',
    website: 'http://playboicarti.com',
    rating: 'High',
    industry: 'Entertainment',
    firstName: 'Playboi',
    lastName: 'Carti',
    emailOptOut: false,
    fax: '555-000-0002',
    mobile: '555-123-4567',
    leadOwner: 'Chris Evans',
    leadStatus: 'Active',
    leadSource: 'Cold Call',
  },
  {
    id: 2,
    dealName: 'Travis Scott Concert',
    stage: 'Negotiation',
    amount: '$500,000',
    closingDate: '2024-08-15',
    owner: 'Mike Johnson',
    accountName: 'Rodeo Inc.',
    contactName: 'Travis Scott',
    type: 'Event',
    source: 'Referral',
    nextStep: 'Finalize contract',
    createdTime: '2024-06-10',
    modifiedTime: '2024-07-20',
  },
  {
    id: 3,
    dealName: 'Lil Uzi Vert Merchandise',
    stage: 'Prospecting',
    amount: '$200,000',
    closingDate: '2024-09-05',
    owner: 'Sarah Williams',
    accountName: 'Eternal Atake LLC',
    contactName: 'Lil Uzi Vert',
    type: 'Merchandise',
    source: 'Online Inquiry',
    nextStep: 'Send proposal',
    createdTime: '2024-06-15',
    modifiedTime: '2024-07-22',
  },
  {
    id: 4,
    dealName: 'Post Malone Tour Sponsorship',
    stage: 'Proposal',
    amount: '$750,000',
    closingDate: '2024-08-30',
    owner: 'James Brown',
    accountName: 'Stoney Enterprises',
    contactName: 'Post Malone',
    type: 'Sponsorship',
    source: 'Social Media',
    nextStep: 'Negotiate terms',
    createdTime: '2024-07-01',
    modifiedTime: '2024-07-24',
  },
  {
    id: 5,
    dealName: 'Cardi B Fashion Line',
    stage: 'Closed Won',
    amount: '$1,000,000',
    closingDate: '2024-07-20',
    owner: 'Emily Davis',
    accountName: 'Bardi Gang Inc.',
    contactName: 'Cardi B',
    type: 'Product Launch',
    source: 'Referral',
    nextStep: 'Launch campaign',
    createdTime: '2024-05-20',
    modifiedTime: '2024-07-20',
  },
  {
    id: 6,
    dealName: '21 Savage Endorsement',
    stage: 'Qualification',
    amount: '$300,000',
    closingDate: '2024-10-10',
    owner: 'Robert Green',
    accountName: 'Savage Mode LLC',
    contactName: '21 Savage',
    type: 'Endorsement',
    source: 'Partner',
    nextStep: 'Initial meeting',
    createdTime: '2024-07-15',
    modifiedTime: '2024-07-25',
  },
  {
    id: 7,
    dealName: 'Migos Advertising Campaign',
    stage: 'Closed Lost',
    amount: '$600,000',
    closingDate: '2024-07-18',
    owner: 'David Smith',
    accountName: 'Culture Inc.',
    contactName: 'Migos',
    type: 'Advertising',
    source: 'Cold Call',
    nextStep: 'Re-evaluate',
    createdTime: '2024-06-05',
    modifiedTime: '2024-07-18',
  },
  {
    id: 8,
    dealName: 'Lil Baby Collaboration',
    stage: 'Proposal',
    amount: '$450,000',
    closingDate: '2024-08-25',
    owner: 'Angela White',
    accountName: '4PF Records',
    contactName: 'Lil Baby',
    type: 'Collaboration',
    source: 'Networking Event',
    nextStep: 'Present proposal',
    createdTime: '2024-06-25',
    modifiedTime: '2024-07-23',
  },
  {
    id: 9,
    dealName: 'DaBaby Music Video',
    stage: 'Negotiation',
    amount: '$350,000',
    closingDate: '2024-09-15',
    owner: 'John Doe',
    accountName: 'Billion Dollar Baby Ent.',
    contactName: 'DaBaby',
    type: 'Video Production',
    source: 'Website',
    nextStep: 'Discuss budget',
    createdTime: '2024-07-05',
    modifiedTime: '2024-07-25',
  },
  {
    id: 10,
    dealName: 'Future Album Release',
    stage: 'Prospecting',
    amount: '$900,000',
    closingDate: '2024-11-01',
    owner: 'Linda Martin',
    accountName: 'Freebandz LLC',
    contactName: 'Future',
    type: 'Album Release',
    source: 'Referral',
    nextStep: 'Schedule meeting',
    createdTime: '2024-07-10',
    modifiedTime: '2024-07-25',
  },
  {
    id: 11,
    dealName: 'Young Thug Brand Deal',
    stage: 'Qualification',
    amount: '$700,000',
    closingDate: '2024-09-30',
    owner: 'Paul Walker',
    accountName: 'YSL Records',
    contactName: 'Young Thug',
    type: 'Brand Deal',
    source: 'Cold Call',
    nextStep: 'Qualify lead',
    createdTime: '2024-07-15',
    modifiedTime: '2024-07-25',
  },
  {
    id: 12,
    dealName: 'Roddy Ricch Sponsorship',
    stage: 'Proposal',
    amount: '$400,000',
    closingDate: '2024-08-28',
    owner: 'Megan Lee',
    accountName: 'Please Excuse Me LLC',
    contactName: 'Roddy Ricch',
    type: 'Sponsorship',
    source: 'Networking Event',
    nextStep: 'Submit proposal',
    createdTime: '2024-07-20',
    modifiedTime: '2024-07-25',
  },
  {
    id: 13,
    dealName: 'Lil Nas X Marketing Campaign',
    stage: 'Negotiation',
    amount: '$550,000',
    closingDate: '2024-10-12',
    owner: 'Henry Clark',
    accountName: 'Montero Productions',
    contactName: 'Lil Nas X',
    type: 'Marketing',
    source: 'Social Media',
    nextStep: 'Review terms',
    createdTime: '2024-06-30',
    modifiedTime: '2024-07-25',
  },
  {
    id: 14,
    dealName: 'Trippie Redd Tour',
    stage: 'Prospecting',
    amount: '$600,000',
    closingDate: '2024-09-25',
    owner: 'Jessica Black',
    accountName: '1400 Entertainment',
    contactName: 'Trippie Redd',
    type: 'Tour',
    source: 'Referral',
    nextStep: 'Contact management',
    createdTime: '2024-07-01',
    modifiedTime: '2024-07-25',
  },
  {
    id: 15,
    dealName: 'Juice WRLD Tribute Album',
    stage: 'Closed Won',
    amount: '$1,200,000',
    closingDate: '2024-07-22',
    owner: 'Michael Grey',
    accountName: 'Grade A Productions',
    contactName: 'Juice WRLD',
    type: 'Album',
    source: 'Referral',
    nextStep: 'Production start',
    createdTime: '2024-05-22',
    modifiedTime: '2024-07-22',
  },
  {
    id: 16,
    dealName: 'Nav Merchandise Deal',
    stage: 'Proposal',
    amount: '$320,000',
    closingDate: '2024-08-20',
    owner: 'Samantha Brown',
    accountName: 'XO Records',
    contactName: 'Nav',
    type: 'Merchandise',
    source: 'Online Inquiry',
    nextStep: 'Negotiate contract',
    createdTime: '2024-07-03',
    modifiedTime: '2024-07-25',
  },
  {
    id: 17,
    dealName: 'A Boogie wit da Hoodie Advertising',
    stage: 'Negotiation',
    amount: '$370,000',
    closingDate: '2024-09-12',
    owner: 'Alice Green',
    accountName: 'Highbridge the Label',
    contactName: 'A Boogie wit da Hoodie',
    type: 'Advertising',
    source: 'Partner',
    nextStep: 'Discuss contract',
    createdTime: '2024-06-28',
    modifiedTime: '2024-07-25',
  },
];

export default dealsData;
